# Generated by Django 5.2.13 on 2026-08-03 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_product_supplier_sku'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('pago', 'Pago'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado'), ('falhou', 'Falhou')], default='aguardando', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('payment_provider', models.CharField(blank=True, max_length=30)),
                ('payment_external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('pix_payload', models.TextField(blank=True, help_text='Copia-e-cola do QR.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='tenancy.device')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout', to='inventory.sale')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ncm_at_time', models.CharField(blank=True, max_length=8)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Item do checkout',
                'verbose_name_plural': 'Itens do checkout',
            },
        ),
        migrations.CreateModel(
            name='UnlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('venda', 'Venda paga'), ('reposicao', 'Reposição'), ('manutencao', 'Manutenção'), ('manual', 'Abertura manual do operador')], default='venda', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_segundos', models.PositiveSmallIntegerField(default=30)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='pos.checkout')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='tenancy.device')),
            ],
            options={
                'verbose_name': 'Abertura de trava',
                'verbose_name_plural': 'Aberturas de trava',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['unit', 'status', 'created_at'], name='pos_checkou_unit_id_64c4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['status', 'expires_at'], name='pos_checkou_status_a27284_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(fields=('unit', 'idempotency_key'), name='uniq_checkout_idem_por_unidade'),
        ),
        migrations.AddIndex(
            model_name='unlocklog',
            index=models.Index(fields=['device', 'granted_at'], name='pos_unlockl_device__73e226_idx'),
        ),
    ]
