# Generated by Django 5.2.13 on 2026-08-03 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_product_supplier_sku'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='focusnfe', max_length=20)),
                ('ref', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando emissão'), ('processando', 'Transmitida, aguardando SEFAZ'), ('autorizado', 'Autorizada'), ('rejeitado', 'Rejeitada pela SEFAZ'), ('contingencia', 'Em contingência offline'), ('cancelado', 'Cancelada'), ('erro', 'Falha de comunicação')], default='pendente', max_length=20)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=44)),
                ('protocolo', models.CharField(blank=True, max_length=20)),
                ('numero', models.CharField(blank=True, max_length=15)),
                ('serie', models.CharField(blank=True, max_length=5)),
                ('xml_url', models.URLField(blank=True, max_length=500)),
                ('danfe_url', models.URLField(blank=True, max_length=500)),
                ('qrcode_url', models.TextField(blank=True)),
                ('codigo_erro', models.CharField(blank=True, max_length=20)),
                ('erro', models.TextField(blank=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('proxima_tentativa', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('transmitido_em', models.DateTimeField(blank=True, null=True)),
                ('autorizado_em', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='tenancy.operator')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal', to='inventory.sale')),
            ],
            options={
                'verbose_name': 'Documento fiscal',
                'verbose_name_plural': 'Documentos fiscais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'proxima_tentativa'], name='fiscal_fisc_status_596c73_idx'), models.Index(fields=['operator', 'status'], name='fiscal_fisc_operato_b19f04_idx')],
            },
        ),
    ]
