# Generated by Django 5.2.13 on 2026-08-02 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Temporariamente nulo até o onboarding novo existir.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='tenancy.operator'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='registrationsession',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
        ),
        migrations.AddField(
            model_name='promotionview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_views', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_stores',
            field=models.ManyToManyField(blank=True, related_name='targeted_promotions', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='processedpaymentevent',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Preenchido só pra pagamento de assinatura de consultora (PRO).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_payments', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='lead',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_carts', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Loja associada (para consultoras)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='userbehaviorlog',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='userplancache',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cache', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['api_key', 'created_at'], name='api_usage_l_api_key_288890_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['endpoint', 'status_code'], name='api_usage_l_endpoin_778a00_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['email', 'term_version'], name='inventory_c_email_9c923d_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['user', 'purpose_flags'], name='inventory_c_user_id_628d20_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['term_version', 'accepted_at'], name='inventory_c_term_ve_99ded9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expiration_date'], name='inventory_i_expirat_be4f39_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['item', 'quantity'], name='inventory_i_item_id_20f608_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug'], name='inventory_s_slug_3148b5_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'plan'], name='inventory_s_owner_i_dc04b3_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['store', 'transaction_type', 'created_at'], name='inventory_s_store_i_d95637_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_0dfd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionview',
            index=models.Index(fields=['promotion', 'store'], name='inventory_p_promoti_3c20ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionview',
            unique_together={('promotion', 'store')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['store', 'phone'], name='inventory_l_store_i_e40536_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('store', 'phone')},
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['store', 'total_quantity'], name='inventory_i_store_i_9b086b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product', 'sale_price'], name='inventory_i_product_7be1e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('store', 'product')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['store', 'session_id'], name='inventory_c_store_i_349268_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='api_keys_key_291dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['owner', 'is_active'], name='api_keys_owner_i_565a54_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['store', 'plan'], name='api_keys_store_i_829231_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['action_type', 'plan_at_time'], name='user_behavi_action__c79fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['created_at'], name='user_behavi_created_122497_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['store', 'action_type'], name='user_behavi_store_i_4693a4_idx'),
        ),
    ]
