# Generated by Django 5.2.13 on 2026-08-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_natura__691460_idx',
        ),
        # ⚠️ RenameField, não Remove+Add: o par destrutivo que o
        # makemigrations gera por padrão APAGARIA a coluna e recriaria
        # vazia. Aqui não há dados, mas o hábito custa caro depois.
        migrations.RenameField(
            model_name='product',
            old_name='natura_sku',
            new_name='supplier_sku',
        ),
        migrations.AddField(
            model_name='product',
            name='aliq_icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota ICMS %'),
        ),
        migrations.AddField(
            model_name='product',
            name='cest',
            field=models.CharField(blank=True, max_length=7, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='product',
            name='cfop',
            field=models.CharField(default='5102', max_length=4, verbose_name='CFOP'),
        ),
        migrations.AddField(
            model_name='product',
            name='csosn',
            field=models.CharField(blank=True, default='102', max_length=3, verbose_name='CSOSN'),
        ),
        migrations.AddField(
            model_name='product',
            name='cst_cofins',
            field=models.CharField(blank=True, default='49', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='cst_icms',
            field=models.CharField(blank=True, max_length=3, verbose_name='CST ICMS'),
        ),
        migrations.AddField(
            model_name='product',
            name='cst_pis',
            field=models.CharField(blank=True, default='49', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='is_age_restricted',
            field=models.BooleanField(default=False, verbose_name='Venda restrita por idade'),
        ),
        migrations.AddField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='product',
            name='origem',
            field=models.CharField(choices=[('0', '0 — Nacional'), ('1', '1 — Estrangeira, importação direta'), ('2', '2 — Estrangeira, adquirida no mercado interno')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_scale',
            field=models.BooleanField(default=False, verbose_name='Vendido a granel (balança)'),
        ),
        migrations.AddField(
            model_name='product',
            name='scale_plu',
            field=models.PositiveIntegerField(blank=True, help_text='Código interno impresso na etiqueta da balança.', null=True, verbose_name='PLU da balança'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, help_text='Usado para sugerir a data de vencimento no recebimento.', null=True, verbose_name='Validade padrão (dias)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_com',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('FD', 'Fardo')], default='UN', max_length=6, verbose_name='Unidade Comercial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='official_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Referência'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier_sku'], name='inventory_p_supplie_68ed65_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ncm'], name='idx_product_ncm'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['requires_scale', 'scale_plu'], name='inventory_p_require_5eaab3_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('requires_scale', True), ('scale_plu__isnull', False)), fields=('scale_plu',), name='uniq_scale_plu_quando_granel'),
        ),
    ]
