# Generated by Django 5.2.13 on 2026-08-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_produto_fiscal_e_balanca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU do Fornecedor'),
        ),
    ]
