# Generated by Django 6.0.2 on 2026-05-18 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_planconfig_promotion_themeconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome descritivo da chave', max_length=100)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('scopes', models.JSONField(default=list, help_text="Lista de scopes: ['read:products', 'read:analytics', 'write:webhooks']")),
                ('rate_limit', models.IntegerField(default=20, help_text='Requisições por minuto')),
                ('monthly_quota', models.IntegerField(default=1000, help_text='Requisições por mês')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiração da chave', null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Usuário dono da chave (opcional para clientes externos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, help_text='Loja associada (para consultoras)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='inventory.store')),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='inventory.apikey')),
            ],
            options={
                'db_table': 'api_usage_logs',
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email do titular (obrigatório se user=null)', max_length=254)),
                ('session_id', models.CharField(blank=True, help_text='ID da sessão para rastreamento de usuários não logados', max_length=100)),
                ('ip_hash', models.CharField(db_index=True, help_text='Hash SHA-256 do IP (anonimização LGPD Art. 12)', max_length=64)),
                ('purpose_flags', models.JSONField(default=list, help_text="Finalidades consentidas: ['essential', 'analytics', ...]")),
                ('term_version', models.CharField(db_index=True, help_text='Versão do termo: v1.0_2026-05', max_length=20)),
                ('accepted_at', models.DateTimeField(db_index=True, help_text='Data/hora da manifestação de vontade')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Data/hora da revogação (se aplicável)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent do dispositivo (truncado no serializer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário autenticado (nulo para pré-cadastro/anônimos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Consentimento LGPD',
                'verbose_name_plural': 'Registros de Consentimento LGPD',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='api_keys_key_291dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['owner', 'is_active'], name='api_keys_owner_i_565a54_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['store', 'plan'], name='api_keys_store_i_829231_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['api_key', 'created_at'], name='api_usage_l_api_key_288890_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['endpoint', 'status_code'], name='api_usage_l_endpoin_778a00_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['email', 'term_version'], name='inventory_c_email_9c923d_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['user', 'purpose_flags'], name='inventory_c_user_id_628d20_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['term_version', 'accepted_at'], name='inventory_c_term_ve_99ded9_idx'),
        ),
    ]
