# Generated by Django 6.0.2 on 2026-05-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_apikey_apiusagelog_consentrecord_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPrivacyConsent',
        ),
    ]
