# Generated by Django 5.2.13 on 2026-05-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_delete_dataprivacyconsent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawlerlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log do Crawler', 'verbose_name_plural': 'Logs do Crawler'},
        ),
        migrations.AlterModelOptions(
            name='inventorybatch',
            options={'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Item de Estoque', 'verbose_name_plural': 'Itens de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-captured_at'], 'verbose_name': 'Histórico de Preço', 'verbose_name_plural': 'Históricos de Preço'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='registrationsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Sessão de Cadastro', 'verbose_name_plural': 'Sessões de Cadastro'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Item de Venda', 'verbose_name_plural': 'Itens de Venda'},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transação de Estoque', 'verbose_name_plural': 'Transações de Estoque'},
        ),
        migrations.AlterField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(default=list, help_text='Lista de scopes permitidos'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='accepted_at',
            field=models.DateTimeField(db_index=True, help_text='Data da manifestação'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email do titular', max_length=254),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='ip_hash',
            field=models.CharField(db_index=True, help_text='Hash SHA-256 do IP', max_length=64),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='purpose_flags',
            field=models.JSONField(default=list, help_text='Finalidades consentidas'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='Data da revogação', null=True),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='session_id',
            field=models.CharField(blank=True, help_text='ID da sessão para anônimos', max_length=100),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='term_version',
            field=models.CharField(db_index=True, help_text='Versão do termo', max_length=20),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User-Agent (truncado no serializer)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='payment_external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', help_text='Plano de assinatura da loja', max_length=20),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='app_name',
            field=models.CharField(default='Minha Amora', max_length=100),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_accent',
            field=models.CharField(default='#A91B60', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_background',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_border',
            field=models.CharField(default='#E5E7EB', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_card',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_destructive',
            field=models.CharField(default='#DC2626', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_primary',
            field=models.CharField(default='#871745', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_primary_light',
            field=models.CharField(default='#FDF2F7', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_success',
            field=models.CharField(default='#2E8B57', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_text',
            field=models.CharField(default='#2D292E', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='color_warning',
            field=models.CharField(default='#F59E0B', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expiration_date'], name='inventory_i_expirat_be4f39_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['item', 'quantity'], name='inventory_i_item_id_20f608_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['store', 'total_quantity'], name='inventory_i_store_i_9b086b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product', 'sale_price'], name='inventory_i_product_7be1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['bar_code'], name='inventory_p_bar_cod_956879_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['natura_sku'], name='inventory_p_natura__691460_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['store', 'transaction_type', 'created_at'], name='inventory_s_store_i_d95637_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_0dfd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug'], name='inventory_s_slug_3148b5_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'plan'], name='inventory_s_owner_i_dc04b3_idx'),
        ),
    ]
