# Generated by Django 5.0.2 on 2026-07-22 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_crawlerlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, help_text='ID da cobrança no Asaas (ex.: pay_080225913252)', max_length=100, unique=True)),
                ('event', models.CharField(blank=True, max_length=50)),
                ('days_granted', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_payments', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Cobrança processada',
                'verbose_name_plural': 'Cobranças processadas',
                'ordering': ['-processed_at'],
            },
        ),
    ]