# Generated by Django 5.0.2 on 2026-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_processedpaymentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
