# Generated by Django 5.0.2 on 2026-07-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_cart_cartitem_lead_cart_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('cartao', 'Cartão de crédito')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='whatsapp_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
