# Generated by Django 5.0.2 on 2026-08-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_cart_payment_confirmed_cart_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedpaymentevent',
            name='billing_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='processedpaymentevent',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
