# Generated by Django 5.0.2 on 2026-08-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_processedpaymentevent_billing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='target_stores',
            field=models.ManyToManyField(blank=True, related_name='targeted_promotions', to='inventory.store'),
        ),
    ]