# Generated by Django 5.0.2 on 2026-08-01 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_promotion_target_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='O sistema está em manutenção programada e pode apresentar instabilidade ou indisponibilidade temporária em algumas funcionalidades. Já estamos de olho — pode continuar usando normalmente.')),
                ('ai_enabled', models.BooleanField(default=True)),
                ('storefront_enabled', models.BooleanField(default=True)),
                ('ocr_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do sistema',
                'verbose_name_plural': 'Configuração do sistema',
            },
        ),
        migrations.CreateModel(
            name='PromotionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='inventory.promotion')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_views', to='inventory.store')),
            ],
            options={
                'indexes': [models.Index(fields=['promotion', 'store'], name='inventory_p_promoti_3c20ae_idx')],
                'unique_together': {('promotion', 'store')},
            },
        ),
    ]