# Generated by Django 5.0.2 on 2026-08-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
        ('inventory', '0017_systemconfig_promotionview'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='developer',
            field=models.ForeignKey(blank=True, help_text='Desenvolvedor dono da chave (produto de API comercial)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='developers.developeraccount'),
        ),
    ]