# Generated by Django 5.0.2 on 2026-08-01 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_apiplanconfig_apisubscription'),
        ('inventory', '0018_apikey_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedpaymentevent',
            name='developer',
            field=models.ForeignKey(blank=True, help_text='Preenchido só pra pagamento de assinatura de API (desenvolvedor).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_payments', to='developers.developeraccount'),
        ),
        migrations.AlterField(
            model_name='processedpaymentevent',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Preenchido só pra pagamento de assinatura de consultora (PRO).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_payments', to='inventory.store'),
        ),
    ]
