# Generated by Django 5.2.13 on 2026-08-02 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome fantasia', max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='Razão social', max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('tax_regime', models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real'), ('mei', 'MEI')], default='simples', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cert_a1_encrypted', models.BinaryField(blank=True, null=True)),
                ('cert_a1_expires_at', models.DateField(blank=True, help_text='Alertar o cliente 30 dias antes: certificado vencido = loja sem emitir nota.', null=True)),
                ('csc_id', models.CharField(blank=True, max_length=10)),
                ('csc_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('fiscal_provider', models.CharField(default='focusnfe', help_text='Hub fiscal usado para emitir NFC-e.', max_length=20)),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'plan'], name='tenancy_ope_is_acti_58ab44_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('totem', 'Totem de autoatendimento'), ('fridge_lock', 'Trava de geladeira'), ('tablet', 'Tablet do repositor'), ('scale', 'Balança')], default='totem', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('firmware', models.CharField(blank=True, max_length=20)),
                ('catalog_hash', models.CharField(blank=True, max_length=64)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='inventory.apikey')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'indexes': [models.Index(fields=['unit', 'kind'], name='tenancy_dev_unit_id_d3d74c_idx'), models.Index(fields=['last_seen'], name='tenancy_dev_last_se_5623a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('manager', 'Gerente'), ('stocker', 'Repositor'), ('viewer', 'Visualizador')], default='owner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('units', models.ManyToManyField(blank=True, help_text='Deixe vazio para dar acesso a todas as unidades da operação.', related_name='members', to='inventory.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.operator')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'indexes': [models.Index(fields=['user', 'is_active'], name='tenancy_mem_user_id_4a284b_idx'), models.Index(fields=['operator', 'role'], name='tenancy_mem_operato_290e8c_idx')],
                'unique_together': {('user', 'operator')},
            },
        ),
    ]
