# Generated by Django 5.2.13 on 2026-08-03 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_product_supplier_sku'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_rota', 'Em rota'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picklists', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Romaneio',
                'verbose_name_plural': 'Romaneios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField(default=0, verbose_name='Ponto de pedido')),
                ('max_qty', models.PositiveIntegerField(default=0, verbose_name='Nível de recompletamento')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=3)),
                ('safety_stock', models.PositiveIntegerField(default=0, verbose_name='Estoque de segurança')),
                ('is_auto', models.BooleanField(default=True, verbose_name='Calcular automaticamente')),
                ('venda_media_diaria', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('calculado_em', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Regra de reposição',
                'verbose_name_plural': 'Regras de reposição',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ruptura_prevista', 'Vai faltar'), ('ruptura_ativa', 'Faltou'), ('validade', 'Validade crítica'), ('dead_stock', 'Produto parado'), ('divergencia', 'Divergência de inventário'), ('device_offline', 'Totem offline')], max_length=30)),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('atencao', 'Atenção'), ('urgente', 'Urgente')], default='atencao', max_length=10)),
                ('titulo', models.CharField(max_length=160)),
                ('detalhe', models.TextField(blank=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('chave', models.CharField(help_text='Identidade do alerta, para deduplicar.', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('lido_em', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tenancy.device')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventoryitem')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-severidade', '-criado_em'],
                'indexes': [models.Index(fields=['unit', 'resolvido_em', 'severidade'], name='replenishme_unit_id_e3422a_idx'), models.Index(fields=['tipo', 'criado_em'], name='replenishme_tipo_d73ac2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolvido_em__isnull', True)), fields=('unit', 'chave'), name='uniq_alerta_aberto_por_chave')],
            },
        ),
        migrations.CreateModel(
            name='PickListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sugerida', models.PositiveIntegerField()),
                ('quantidade_reposta', models.PositiveIntegerField(blank=True, null=True)),
                ('estoque_no_momento', models.PositiveIntegerField(default=0)),
                ('cobertura_dias', models.FloatField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='replenishment.picklist')),
            ],
            options={
                'verbose_name': 'Item do romaneio',
                'verbose_name_plural': 'Itens do romaneio',
                'unique_together': {('picklist', 'item')},
            },
        ),
    ]
