# Generated by Django 5.0.2 on 2026-08-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developeraccount',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='developeraccount',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
