# Generated by Django 5.0.2 on 2026-08-01 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developeraccount_firebase_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_quota', models.IntegerField(default=1000)),
                ('rate_limit', models.IntegerField(default=20, help_text='Requisições por minuto')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano de API',
                'verbose_name_plural': 'Planos de API',
            },
        ),
        migrations.CreateModel(
            name='ApiSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_external_id', models.CharField(blank=True, max_length=100)),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='developers.developeraccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='developers.apiplanconfig')),
            ],
            options={
                'verbose_name': 'Assinatura de API',
                'verbose_name_plural': 'Assinaturas de API',
            },
        ),
    ]
